import {
  AbsoluteFill,
  CalculateMetadataFunction,
  Composition,
  Easing,
  Interactive,
  interpolate,
  staticFile,
  useCurrentFrame,
  useVideoConfig,
} from "remotion";
import { Audio } from "@remotion/media";
import { Input, ALL_FORMATS, UrlSource } from "mediabunny";
import { loadFont } from "@remotion/google-fonts/BeVietnamPro";
import { VNIndexBar } from "./fetchVNIndex";

const { fontFamily } = loadFont("normal", {
  weights: ["400", "500", "700", "800"],
  subsets: ["latin", "vietnamese"],
});

const WIDTH = 1080;
const HEIGHT = 1080;
const FPS = 30;
const DEFAULT_DURATION_IN_FRAMES = 60 * FPS;
const MAX_DURATION_IN_FRAMES = 90 * FPS; // safety cap in case the narration runs long
// Entrance animation settles by ~150f; everything after that is a slow ambient
// idle loop (glow orb, breathing badge, traveling chart marker) so the rest of
// the video isn't just a frozen frame.
const IDLE_START = 150;
// Matches the `from` prop on the <Audio> element below — the frame offset at
// which narration starts, used to convert beats.json timestamps to frames.
const AUDIO_START_FRAME = 20;

type Beat = { startMs: number; text: string };
type Beats = Partial<Record<"hook" | "headline" | "todayDetail" | "range30" | "trend30" | "outro", Beat>>;

type Props = {
  bars: VNIndexBar[];
  hasVoiceover: boolean;
  beats: Beats | null;
};

const calculateMetadata: CalculateMetadataFunction<Props> = async ({
  abortSignal,
}) => {
  // Data is pre-fetched into public/vnindex.json by `npm run fetch-data`
  // (see scripts/fetch-vnindex.mjs) — VNDirect's bot-protection blocks requests
  // made directly from the headless render browser, so we can't fetch it here.
  const response = await fetch(staticFile("vnindex.json"), { signal: abortSignal });

  if (!response.ok) {
    throw new Error(
      `Could not read public/vnindex.json (${response.status}). Run "npm run fetch-data" first.`,
    );
  }

  const bars = (await response.json()) as VNIndexBar[];

  // Voiceover is optional (generated by scripts/generate-voiceover.mjs via the
  // free Microsoft Edge TTS service — no API key needed), so check whether the
  // file exists rather than assuming it does.
  const voiceoverUrl = staticFile("voiceover/vnindex-latest.mp3");
  const voiceoverCheck = await fetch(voiceoverUrl, {
    method: "HEAD",
    signal: abortSignal,
  }).catch(() => null);
  const hasVoiceover = Boolean(voiceoverCheck && voiceoverCheck.ok);

  // Beats (per-sentence start times) are optional too — written by
  // generate-voiceover.mjs only when Edge TTS's sentence-boundary count
  // matched our script exactly. Used to sync visual "beats" to the narration.
  let beats: Beats | null = null;
  if (hasVoiceover) {
    const beatsResponse = await fetch(staticFile("voiceover/vnindex-latest.beats.json"), {
      signal: abortSignal,
    }).catch(() => null);
    if (beatsResponse && beatsResponse.ok) {
      beats = (await beatsResponse.json()) as Beats;
    }
  }

  // Size the video to the narration so it's never cut off mid-sentence: default
  // to 60s, but stretch (up to a cap) if the generated voiceover runs longer.
  let durationInFrames = DEFAULT_DURATION_IN_FRAMES;
  if (hasVoiceover) {
    try {
      const input = new Input({ formats: ALL_FORMATS, source: new UrlSource(voiceoverUrl) });
      const audioDurationInSeconds = await input.computeDuration();
      const neededFrames = Math.ceil((audioDurationInSeconds + 1) * FPS); // +1s tail padding
      durationInFrames = Math.min(
        MAX_DURATION_IN_FRAMES,
        Math.max(DEFAULT_DURATION_IN_FRAMES, neededFrames),
      );
    } catch {
      // If duration probing fails for any reason, fall back to the default
      // length rather than failing the whole render.
    }
  }

  return {
    durationInFrames,
    props: { bars, hasVoiceover, beats },
  };
};

export const VNIndexPostcardComposition = () => {
  return (
    <Composition
      id="VNIndexPostcard"
      component={VNIndexPostcard}
      durationInFrames={DEFAULT_DURATION_IN_FRAMES}
      fps={FPS}
      width={WIDTH}
      height={HEIGHT}
      defaultProps={{ bars: [] as VNIndexBar[], hasVoiceover: false, beats: null }}
      calculateMetadata={calculateMetadata}
    />
  );
};

const formatPoints = (n: number) =>
  n.toLocaleString("vi-VN", { minimumFractionDigits: 2, maximumFractionDigits: 2 });

const formatVolume = (v: number) => {
  if (v >= 1_000_000) return `${(v / 1_000_000).toFixed(1)} triệu CP`;
  if (v >= 1_000) return `${(v / 1_000).toFixed(1)} nghìn CP`;
  return `${v} CP`;
};

const formatDate = (unixSeconds: number) => {
  const d = new Date(unixSeconds * 1000);
  return d.toLocaleDateString("vi-VN", {
    weekday: "long",
    day: "2-digit",
    month: "2-digit",
    year: "numeric",
  });
};

// A quick attack / hold / decay pulse curve (0 -> 1 -> 0) starting at `startFrame`.
// Used to flash/emphasize an element right when the narrator mentions it.
const pulseAt = (
  frame: number,
  startFrame: number | undefined,
  attack = 6,
  hold = 8,
  decay = 26,
) => {
  if (startFrame === undefined) return 0;
  return interpolate(
    frame,
    [startFrame, startFrame + attack, startFrame + attack + hold, startFrame + attack + hold + decay],
    [0, 1, 1, 0],
    { extrapolateLeft: "clamp", extrapolateRight: "clamp" },
  );
};

export const VNIndexPostcard: React.FC<Props> = ({ bars, hasVoiceover, beats }) => {
  const frame = useCurrentFrame();

  if (!bars || bars.length < 2) {
    return (
      <AbsoluteFill
        style={{
          backgroundColor: "#0b1220",
          color: "white",
          fontFamily,
          fontSize: 44,
          justifyContent: "center",
          alignItems: "center",
          textAlign: "center",
          padding: 80,
        }}
      >
        Không tải được dữ liệu VN-Index
      </AbsoluteFill>
    );
  }

  const latest = bars[bars.length - 1];
  const previous = bars[bars.length - 2];
  const change = latest.close - previous.close;
  const changePercent = (change / previous.close) * 100;
  const isUp = change > 0;
  const isFlat = Math.abs(change) < 0.005;

  // VN market convention: up = red, down = green, flat = yellow.
  const accentColor = isFlat ? "#eab308" : isUp ? "#ef4444" : "#22c55e";
  const accentColorSoft = isFlat
    ? "rgba(234,179,8,0.15)"
    : isUp
      ? "rgba(239,68,68,0.15)"
      : "rgba(34,197,94,0.15)";

  let upDays = 0;
  let downDays = 0;
  for (let i = 1; i < bars.length; i++) {
    if (bars[i].close > bars[i - 1].close) upDays++;
    else if (bars[i].close < bars[i - 1].close) downDays++;
  }

  // --- Voiceover sync beats ---
  // Convert each beats.json timestamp (ms into the narration) to an absolute
  // frame, offset by where the <Audio> track actually starts.
  const beatFrame = (id: keyof Beats) => {
    const beat = beats?.[id];
    if (!beat) return undefined;
    return AUDIO_START_FRAME + Math.round((beat.startMs / 1000) * FPS);
  };
  const headlineBeat = beatFrame("headline");
  const todayDetailBeat = beatFrame("todayDetail");
  const range30Beat = beatFrame("range30");
  const trend30Beat = beatFrame("trend30");

  const headlinePulse = pulseAt(frame, headlineBeat);
  const todayDetailPulse = pulseAt(frame, todayDetailBeat);
  const range30Pulse = pulseAt(frame, range30Beat, 10, 14, 50);
  // The up/down-days stat row appears (and stays) once the narrator reaches it;
  // fall back to right after the chart finishes drawing when there's no sync data.
  const trendRowIn = interpolate(frame, [trend30Beat ?? 150, (trend30Beat ?? 150) + 18], [0, 1], {
    extrapolateLeft: "clamp",
    extrapolateRight: "clamp",
    easing: Easing.bezier(0.16, 1, 0.3, 1),
  });

  // --- Animations ---
  const cardIn = interpolate(frame, [0, 18], [0, 1], {
    extrapolateLeft: "clamp",
    extrapolateRight: "clamp",
    easing: Easing.bezier(0.16, 1, 0.3, 1),
  });

  const headerIn = interpolate(frame, [8, 26], [0, 1], {
    extrapolateLeft: "clamp",
    extrapolateRight: "clamp",
    easing: Easing.bezier(0.16, 1, 0.3, 1),
  });

  const numberProgress = interpolate(frame, [16, 55], [0, 1], {
    extrapolateLeft: "clamp",
    extrapolateRight: "clamp",
    easing: Easing.out(Easing.cubic),
  });
  const displayedClose = previous.close + (latest.close - previous.close) * numberProgress;

  const badgeIn = interpolate(frame, [45, 65], [0, 1], {
    extrapolateLeft: "clamp",
    extrapolateRight: "clamp",
    easing: Easing.bezier(0.16, 1, 0.3, 1),
  });

  const chartIn = interpolate(frame, [55, 130], [0, 1], {
    extrapolateLeft: "clamp",
    extrapolateRight: "clamp",
    easing: Easing.bezier(0.16, 1, 0.3, 1),
  });

  const footerIn = interpolate(frame, [110, 130], [0, 1], {
    extrapolateLeft: "clamp",
    extrapolateRight: "clamp",
    easing: Easing.bezier(0.16, 1, 0.3, 1),
  });

  // --- Ambient idle loop (keeps the remaining ~58s alive without new data) ---
  const idleT = Math.max(0, frame - IDLE_START) / FPS; // seconds since idle started
  const orbX = 50 + Math.sin(idleT * 0.35) * 22;
  const orbY = 42 + Math.cos(idleT * 0.27) * 18;
  const badgeBreathe = 1 + Math.sin(idleT * Math.PI * 0.5) * 0.02;
  const glowPulse = 0.5 + Math.sin(idleT * Math.PI * 0.5) * 0.15;

  // Marker that slowly travels back and forth along the trend line.
  const travelLoop = 6 * FPS; // 6s to cross the chart, then reverse
  const travelRaw = (Math.max(0, frame - IDLE_START) % (travelLoop * 2)) / travelLoop;
  const travelT = travelRaw <= 1 ? travelRaw : 2 - travelRaw; // 0->1->0 ping-pong

  // --- Chart geometry ---
  const chartWidth = WIDTH - 160;
  const chartHeight = 250;
  const closes = bars.map((b) => b.close);
  const minClose = Math.min(...closes);
  const maxClose = Math.max(...closes);
  const range = maxClose - minClose || 1;

  const points = bars.map((b, i) => {
    const x = (i / (bars.length - 1)) * chartWidth;
    const y = chartHeight - ((b.close - minClose) / range) * chartHeight;
    return { x, y };
  });

  const linePath = points
    .map((p, i) => `${i === 0 ? "M" : "L"} ${p.x.toFixed(2)} ${p.y.toFixed(2)}`)
    .join(" ");

  const areaPath = `${linePath} L ${chartWidth} ${chartHeight} L 0 ${chartHeight} Z`;

  // Position of the ambient traveling marker along the polyline at travelT (0..1).
  const travelX = travelT * chartWidth;
  let travelPoint = points[points.length - 1];
  for (let i = 0; i < points.length - 1; i++) {
    if (travelX >= points[i].x && travelX <= points[i + 1].x) {
      const segT = (travelX - points[i].x) / (points[i + 1].x - points[i].x || 1);
      travelPoint = {
        x: travelX,
        y: points[i].y + (points[i + 1].y - points[i].y) * segT,
      };
      break;
    }
  }

  return (
    <AbsoluteFill
      style={{
        fontFamily,
        background: "linear-gradient(160deg, #0b1220 0%, #111c33 55%, #0b1220 100%)",
      }}
    >
      {hasVoiceover && (
        <Audio src={staticFile("voiceover/vnindex-latest.mp3")} from={20} />
      )}

      {/* Ambient glow orb, slowly drifting behind the card */}
      <div
        style={{
          position: "absolute",
          left: `${orbX}%`,
          top: `${orbY}%`,
          translate: "-50% -50%",
          width: 640,
          height: 640,
          borderRadius: "50%",
          background: accentColor,
          opacity: glowPulse * 0.18,
          filter: "blur(140px)",
        }}
      />

      <AbsoluteFill
        style={{
          justifyContent: "center",
          alignItems: "center",
        }}
      >
        <Interactive.Div
          name="Card"
          style={{
            width: WIDTH - 96,
            height: HEIGHT - 96,
            borderRadius: 40,
            border: "1px solid rgba(255,255,255,0.08)",
            background: "rgba(255,255,255,0.03)",
            boxShadow: "0 40px 80px rgba(0,0,0,0.5)",
            scale: interpolate(cardIn, [0, 1], [0.94, 1], {
              easing: Easing.bezier(0.16, 1, 0.3, 1),
              output: "perceptual-scale",
            }),
            opacity: cardIn,
            display: "flex",
            flexDirection: "column",
            alignItems: "center",
            padding: "56px 64px 36px",
          }}
        >
          {/* Header */}
          <Interactive.Div
            name="Header"
            style={{
              opacity: headerIn,
              translate: `0px ${interpolate(headerIn, [0, 1], [12, 0])}px`,
              display: "flex",
              flexDirection: "column",
              alignItems: "center",
              gap: 8,
            }}
          >
            <div
              style={{
                fontSize: 30,
                letterSpacing: 6,
                fontWeight: 700,
                color: "rgba(255,255,255,0.55)",
              }}
            >
              VN-INDEX · HOSE
            </div>
            <div
              style={{
                fontSize: 26,
                fontWeight: 400,
                color: "rgba(255,255,255,0.4)",
                textTransform: "capitalize",
              }}
            >
              {formatDate(latest.time)}
            </div>
          </Interactive.Div>

          {/* Big number */}
          <Interactive.Div
            name="BigNumber"
            style={{
              marginTop: 32,
              fontSize: 150,
              fontWeight: 800,
              color: "white",
              lineHeight: 1,
              letterSpacing: -2,
              scale: 1 + headlinePulse * 0.035,
              textShadow: `0 0 ${headlinePulse * 60}px ${accentColor}${headlinePulse > 0.05 ? "aa" : "00"}`,
            }}
          >
            {formatPoints(displayedClose)}
          </Interactive.Div>

          {/* Change badge */}
          <Interactive.Div
            name="ChangeBadge"
            style={{
              marginTop: 20,
              opacity: badgeIn,
              scale:
                interpolate(badgeIn, [0, 1], [0.9, 1], {
                  easing: Easing.spring({ damping: 200 }),
                  output: "perceptual-scale",
                }) *
                badgeBreathe *
                (1 + headlinePulse * 0.05),
              display: "flex",
              alignItems: "center",
              gap: 12,
              padding: "12px 28px",
              borderRadius: 999,
              background: accentColorSoft,
              border: `1px solid ${accentColor}55`,
            }}
          >
            <div style={{ fontSize: 40, fontWeight: 700, color: accentColor }}>
              {isFlat ? "◆" : isUp ? "▲" : "▼"}
            </div>
            <div style={{ fontSize: 40, fontWeight: 700, color: accentColor }}>
              {isUp ? "+" : ""}
              {formatPoints(change)} ({isUp ? "+" : ""}
              {changePercent.toFixed(2)}%)
            </div>
          </Interactive.Div>

          {/* Chart */}
          <Interactive.Div
            name="Chart"
            style={{
              marginTop: 36,
              width: chartWidth,
              scale: 1 + range30Pulse * 0.02,
              opacity: interpolate(chartIn, [0, 0.3], [0, 1], {
                extrapolateLeft: "clamp",
                extrapolateRight: "clamp",
              }),
            }}
          >
            <svg
              width={chartWidth}
              height={chartHeight}
              viewBox={`0 0 ${chartWidth} ${chartHeight}`}
            >
              <defs>
                <linearGradient id="areaFill" x1="0" y1="0" x2="0" y2="1">
                  <stop offset="0%" stopColor={accentColor} stopOpacity={0.35} />
                  <stop offset="100%" stopColor={accentColor} stopOpacity={0} />
                </linearGradient>
                <linearGradient id="sweepFill" x1="0" y1="0" x2="1" y2="0">
                  <stop offset="0%" stopColor="white" stopOpacity={0} />
                  <stop offset="50%" stopColor="white" stopOpacity={0.9} />
                  <stop offset="100%" stopColor="white" stopOpacity={0} />
                </linearGradient>
              </defs>
              <path d={areaPath} fill="url(#areaFill)" opacity={chartIn} />
              {/* Highlight sweep across the 30-day range, timed to the "range30" narration beat */}
              {range30Pulse > 0.01 && (
                <rect
                  x={
                    interpolate(
                      frame,
                      [range30Beat ?? 0, (range30Beat ?? 0) + 74],
                      [-60, chartWidth + 60],
                      { extrapolateLeft: "clamp", extrapolateRight: "clamp" },
                    ) - 60
                  }
                  y={-10}
                  width={120}
                  height={chartHeight + 20}
                  fill="url(#sweepFill)"
                  opacity={range30Pulse * 0.6}
                />
              )}
              <path
                d={linePath}
                fill="none"
                stroke={accentColor}
                strokeWidth={5}
                strokeLinecap="round"
                strokeLinejoin="round"
                pathLength={1}
                strokeDasharray={1}
                strokeDashoffset={interpolate(chartIn, [0, 1], [1, 0])}
              />
              {/* Ambient marker slowly traveling along the trend line */}
              <circle
                cx={travelPoint.x}
                cy={travelPoint.y}
                r={18}
                fill={accentColor}
                opacity={chartIn * 0.25}
              />
              <circle
                cx={travelPoint.x}
                cy={travelPoint.y}
                r={7}
                fill={accentColor}
                stroke="white"
                strokeWidth={2}
                opacity={chartIn}
              />
            </svg>
            <div
              style={{
                display: "flex",
                justifyContent: "space-between",
                marginTop: 12,
                fontSize: 26,
                color: "rgba(255,255,255,0.45)",
              }}
            >
              <span>{formatDate(bars[0].time).split(",")[0]}</span>
              <span>30 phiên gần nhất</span>
              <span>{formatDate(latest.time).split(",")[0]}</span>
            </div>
          </Interactive.Div>

          {/* Up/down days — revealed in sync with the "trend30" narration beat */}
          <Interactive.Div
            name="TrendDaysRow"
            style={{
              marginTop: 14,
              opacity: trendRowIn,
              translate: `0px ${interpolate(trendRowIn, [0, 1], [10, 0])}px`,
              display: "flex",
              gap: 16,
            }}
          >
            <div
              style={{
                display: "flex",
                alignItems: "center",
                gap: 8,
                padding: "8px 18px",
                borderRadius: 999,
                background: "rgba(239,68,68,0.12)",
                border: "1px solid rgba(239,68,68,0.35)",
                fontSize: 22,
                fontWeight: 700,
                color: "#ef4444",
              }}
            >
              ▲ {upDays} phiên tăng
            </div>
            <div
              style={{
                display: "flex",
                alignItems: "center",
                gap: 8,
                padding: "8px 18px",
                borderRadius: 999,
                background: "rgba(34,197,94,0.12)",
                border: "1px solid rgba(34,197,94,0.35)",
                fontSize: 22,
                fontWeight: 700,
                color: "#22c55e",
              }}
            >
              ▼ {downDays} phiên giảm
            </div>
          </Interactive.Div>

          {/* Footer */}
          <Interactive.Div
            name="Footer"
            style={{
              marginTop: "auto",
              opacity: footerIn,
              width: "100%",
              display: "flex",
              justifyContent: "space-between",
              alignItems: "center",
              paddingTop: 20,
              borderTop: "1px solid rgba(255,255,255,0.08)",
              fontSize: 26,
              color: "rgba(255,255,255,0.5)",
            }}
          >
            <span
              style={{
                color: `rgba(255,255,255,${0.5 + todayDetailPulse * 0.5})`,
                scale: 1 + todayDetailPulse * 0.06,
              }}
            >
              KLGD: {formatVolume(latest.volume)}
            </span>
            <span>Nguồn: VNDirect</span>
          </Interactive.Div>
        </Interactive.Div>
      </AbsoluteFill>
    </AbsoluteFill>
  );
};
