import {
  AbsoluteFill,
  CalculateMetadataFunction,
  Composition,
  Easing,
  Interactive,
  interpolate,
  staticFile,
  useCurrentFrame,
  useVideoConfig,
} from "remotion";
import { Audio } from "@remotion/media";
import { Input, ALL_FORMATS, UrlSource } from "mediabunny";
import { loadFont } from "@remotion/google-fonts/BeVietnamPro";
import { VNIndexBar } from "./fetchVNIndex";

const { fontFamily } = loadFont("normal", {
  weights: ["400", "500", "700", "800"],
  subsets: ["latin", "vietnamese"],
});

const WIDTH = 1080;
const HEIGHT = 1080;
const FPS = 30;
const DEFAULT_DURATION_IN_FRAMES = 60 * FPS;
const MAX_DURATION_IN_FRAMES = 90 * FPS; // safety cap in case the narration runs long
// Entrance animation settles by ~150f; everything after that is a slow ambient
// idle loop (glow orb, breathing badge, traveling chart marker) so the rest of
// the video isn't just a frozen frame.
const IDLE_START = 150;

type Props = {
  bars: VNIndexBar[];
  hasVoiceover: boolean;
};

const calculateMetadata: CalculateMetadataFunction<Props> = async ({
  abortSignal,
}) => {
  // Data is pre-fetched into public/vnindex.json by `npm run fetch-data`
  // (see scripts/fetch-vnindex.mjs) — VNDirect's bot-protection blocks requests
  // made directly from the headless render browser, so we can't fetch it here.
  const response = await fetch(staticFile("vnindex.json"), { signal: abortSignal });

  if (!response.ok) {
    throw new Error(
      `Could not read public/vnindex.json (${response.status}). Run "npm run fetch-data" first.`,
    );
  }

  const bars = (await response.json()) as VNIndexBar[];

  // Voiceover is optional (generated by scripts/generate-voiceover.mjs via the
  // free Microsoft Edge TTS service — no API key needed), so check whether the
  // file exists rather than assuming it does.
  const voiceoverUrl = staticFile("voiceover/vnindex-latest.mp3");
  const voiceoverCheck = await fetch(voiceoverUrl, {
    method: "HEAD",
    signal: abortSignal,
  }).catch(() => null);
  const hasVoiceover = Boolean(voiceoverCheck && voiceoverCheck.ok);

  // Size the video to the narration so it's never cut off mid-sentence: default
  // to 60s, but stretch (up to a cap) if the generated voiceover runs longer.
  let durationInFrames = DEFAULT_DURATION_IN_FRAMES;
  if (hasVoiceover) {
    try {
      const input = new Input({ formats: ALL_FORMATS, source: new UrlSource(voiceoverUrl) });
      const audioDurationInSeconds = await input.computeDuration();
      const neededFrames = Math.ceil((audioDurationInSeconds + 1) * FPS); // +1s tail padding
      durationInFrames = Math.min(
        MAX_DURATION_IN_FRAMES,
        Math.max(DEFAULT_DURATION_IN_FRAMES, neededFrames),
      );
    } catch {
      // If duration probing fails for any reason, fall back to the default
      // length rather than failing the whole render.
    }
  }

  return {
    durationInFrames,
    props: { bars, hasVoiceover },
  };
};

export const VNIndexPostcardComposition = () => {
  return (
    <Composition
      id="VNIndexPostcard"
      component={VNIndexPostcard}
      durationInFrames={DEFAULT_DURATION_IN_FRAMES}
      fps={FPS}
      width={WIDTH}
      height={HEIGHT}
      defaultProps={{ bars: [] as VNIndexBar[], hasVoiceover: false }}
      calculateMetadata={calculateMetadata}
    />
  );
};

const formatPoints = (n: number) =>
  n.toLocaleString("vi-VN", { minimumFractionDigits: 2, maximumFractionDigits: 2 });

const formatVolume = (v: number) => {
  if (v >= 1_000_000) return `${(v / 1_000_000).toFixed(1)} triệu CP`;
  if (v >= 1_000) return `${(v / 1_000).toFixed(1)} nghìn CP`;
  return `${v} CP`;
};

const formatDate = (unixSeconds: number) => {
  const d = new Date(unixSeconds * 1000);
  return d.toLocaleDateString("vi-VN", {
    weekday: "long",
    day: "2-digit",
    month: "2-digit",
    year: "numeric",
  });
};

export const VNIndexPostcard: React.FC<Props> = ({ bars, hasVoiceover }) => {
  const frame = useCurrentFrame();

  if (!bars || bars.length < 2) {
    return (
      <AbsoluteFill
        style={{
          backgroundColor: "#0b1220",
          color: "white",
          fontFamily,
          fontSize: 44,
          justifyContent: "center",
          alignItems: "center",
          textAlign: "center",
          padding: 80,
        }}
      >
        Không tải được dữ liệu VN-Index
      </AbsoluteFill>
    );
  }

  const latest = bars[bars.length - 1];
  const previous = bars[bars.length - 2];
  const change = latest.close - previous.close;
  const changePercent = (change / previous.close) * 100;
  const isUp = change > 0;
  const isFlat = Math.abs(change) < 0.005;

  // VN market convention: up = red, down = green, flat = yellow.
  const accentColor = isFlat ? "#eab308" : isUp ? "#ef4444" : "#22c55e";
  const accentColorSoft = isFlat
    ? "rgba(234,179,8,0.15)"
    : isUp
      ? "rgba(239,68,68,0.15)"
      : "rgba(34,197,94,0.15)";

  // --- Animations ---
  const cardIn = interpolate(frame, [0, 18], [0, 1], {
    extrapolateLeft: "clamp",
    extrapolateRight: "clamp",
    easing: Easing.bezier(0.16, 1, 0.3, 1),
  });

  const headerIn = interpolate(frame, [8, 26], [0, 1], {
    extrapolateLeft: "clamp",
    extrapolateRight: "clamp",
    easing: Easing.bezier(0.16, 1, 0.3, 1),
  });

  const numberProgress = interpolate(frame, [16, 55], [0, 1], {
    extrapolateLeft: "clamp",
    extrapolateRight: "clamp",
    easing: Easing.out(Easing.cubic),
  });
  const displayedClose = previous.close + (latest.close - previous.close) * numberProgress;

  const badgeIn = interpolate(frame, [45, 65], [0, 1], {
    extrapolateLeft: "clamp",
    extrapolateRight: "clamp",
    easing: Easing.bezier(0.16, 1, 0.3, 1),
  });

  const chartIn = interpolate(frame, [55, 130], [0, 1], {
    extrapolateLeft: "clamp",
    extrapolateRight: "clamp",
    easing: Easing.bezier(0.16, 1, 0.3, 1),
  });

  const footerIn = interpolate(frame, [110, 130], [0, 1], {
    extrapolateLeft: "clamp",
    extrapolateRight: "clamp",
    easing: Easing.bezier(0.16, 1, 0.3, 1),
  });

  // --- Ambient idle loop (keeps the remaining ~58s alive without new data) ---
  const idleT = Math.max(0, frame - IDLE_START) / FPS; // seconds since idle started
  const orbX = 50 + Math.sin(idleT * 0.35) * 22;
  const orbY = 42 + Math.cos(idleT * 0.27) * 18;
  const badgeBreathe = 1 + Math.sin(idleT * Math.PI * 0.5) * 0.02;
  const glowPulse = 0.5 + Math.sin(idleT * Math.PI * 0.5) * 0.15;

  // Marker that slowly travels back and forth along the trend line.
  const travelLoop = 6 * FPS; // 6s to cross the chart, then reverse
  const travelRaw = (Math.max(0, frame - IDLE_START) % (travelLoop * 2)) / travelLoop;
  const travelT = travelRaw <= 1 ? travelRaw : 2 - travelRaw; // 0->1->0 ping-pong

  // --- Chart geometry ---
  const chartWidth = WIDTH - 160;
  const chartHeight = 300;
  const closes = bars.map((b) => b.close);
  const minClose = Math.min(...closes);
  const maxClose = Math.max(...closes);
  const range = maxClose - minClose || 1;

  const points = bars.map((b, i) => {
    const x = (i / (bars.length - 1)) * chartWidth;
    const y = chartHeight - ((b.close - minClose) / range) * chartHeight;
    return { x, y };
  });

  const linePath = points
    .map((p, i) => `${i === 0 ? "M" : "L"} ${p.x.toFixed(2)} ${p.y.toFixed(2)}`)
    .join(" ");

  const areaPath = `${linePath} L ${chartWidth} ${chartHeight} L 0 ${chartHeight} Z`;

  // Position of the ambient traveling marker along the polyline at travelT (0..1).
  const travelX = travelT * chartWidth;
  let travelPoint = points[points.length - 1];
  for (let i = 0; i < points.length - 1; i++) {
    if (travelX >= points[i].x && travelX <= points[i + 1].x) {
      const segT = (travelX - points[i].x) / (points[i + 1].x - points[i].x || 1);
      travelPoint = {
        x: travelX,
        y: points[i].y + (points[i + 1].y - points[i].y) * segT,
      };
      break;
    }
  }

  return (
    <AbsoluteFill
      style={{
        fontFamily,
        background: "linear-gradient(160deg, #0b1220 0%, #111c33 55%, #0b1220 100%)",
      }}
    >
      {hasVoiceover && (
        <Audio src={staticFile("voiceover/vnindex-latest.mp3")} from={20} />
      )}

      {/* Ambient glow orb, slowly drifting behind the card */}
      <div
        style={{
          position: "absolute",
          left: `${orbX}%`,
          top: `${orbY}%`,
          translate: "-50% -50%",
          width: 640,
          height: 640,
          borderRadius: "50%",
          background: accentColor,
          opacity: glowPulse * 0.18,
          filter: "blur(140px)",
        }}
      />

      <AbsoluteFill
        style={{
          justifyContent: "center",
          alignItems: "center",
        }}
      >
        <Interactive.Div
          name="Card"
          style={{
            width: WIDTH - 96,
            height: HEIGHT - 96,
            borderRadius: 40,
            border: "1px solid rgba(255,255,255,0.08)",
            background: "rgba(255,255,255,0.03)",
            boxShadow: "0 40px 80px rgba(0,0,0,0.5)",
            scale: interpolate(cardIn, [0, 1], [0.94, 1], {
              easing: Easing.bezier(0.16, 1, 0.3, 1),
              output: "perceptual-scale",
            }),
            opacity: cardIn,
            display: "flex",
            flexDirection: "column",
            alignItems: "center",
            padding: "72px 64px 56px",
          }}
        >
          {/* Header */}
          <Interactive.Div
            name="Header"
            style={{
              opacity: headerIn,
              translate: `0px ${interpolate(headerIn, [0, 1], [12, 0])}px`,
              display: "flex",
              flexDirection: "column",
              alignItems: "center",
              gap: 8,
            }}
          >
            <div
              style={{
                fontSize: 30,
                letterSpacing: 6,
                fontWeight: 700,
                color: "rgba(255,255,255,0.55)",
              }}
            >
              VN-INDEX · HOSE
            </div>
            <div
              style={{
                fontSize: 26,
                fontWeight: 400,
                color: "rgba(255,255,255,0.4)",
                textTransform: "capitalize",
              }}
            >
              {formatDate(latest.time)}
            </div>
          </Interactive.Div>

          {/* Big number */}
          <Interactive.Div
            name="BigNumber"
            style={{
              marginTop: 44,
              fontSize: 168,
              fontWeight: 800,
              color: "white",
              lineHeight: 1,
              letterSpacing: -2,
            }}
          >
            {formatPoints(displayedClose)}
          </Interactive.Div>

          {/* Change badge */}
          <Interactive.Div
            name="ChangeBadge"
            style={{
              marginTop: 28,
              opacity: badgeIn,
              scale:
                interpolate(badgeIn, [0, 1], [0.9, 1], {
                  easing: Easing.spring({ damping: 200 }),
                  output: "perceptual-scale",
                }) * badgeBreathe,
              display: "flex",
              alignItems: "center",
              gap: 12,
              padding: "16px 32px",
              borderRadius: 999,
              background: accentColorSoft,
              border: `1px solid ${accentColor}55`,
            }}
          >
            <div style={{ fontSize: 48, fontWeight: 700, color: accentColor }}>
              {isFlat ? "◆" : isUp ? "▲" : "▼"}
            </div>
            <div style={{ fontSize: 48, fontWeight: 700, color: accentColor }}>
              {isUp ? "+" : ""}
              {formatPoints(change)} ({isUp ? "+" : ""}
              {changePercent.toFixed(2)}%)
            </div>
          </Interactive.Div>

          {/* Chart */}
          <Interactive.Div
            name="Chart"
            style={{
              marginTop: 56,
              width: chartWidth,
              opacity: interpolate(chartIn, [0, 0.3], [0, 1], {
                extrapolateLeft: "clamp",
                extrapolateRight: "clamp",
              }),
            }}
          >
            <svg
              width={chartWidth}
              height={chartHeight}
              viewBox={`0 0 ${chartWidth} ${chartHeight}`}
            >
              <defs>
                <linearGradient id="areaFill" x1="0" y1="0" x2="0" y2="1">
                  <stop offset="0%" stopColor={accentColor} stopOpacity={0.35} />
                  <stop offset="100%" stopColor={accentColor} stopOpacity={0} />
                </linearGradient>
              </defs>
              <path d={areaPath} fill="url(#areaFill)" opacity={chartIn} />
              <path
                d={linePath}
                fill="none"
                stroke={accentColor}
                strokeWidth={5}
                strokeLinecap="round"
                strokeLinejoin="round"
                pathLength={1}
                strokeDasharray={1}
                strokeDashoffset={interpolate(chartIn, [0, 1], [1, 0])}
              />
              {/* Ambient marker slowly traveling along the trend line */}
              <circle
                cx={travelPoint.x}
                cy={travelPoint.y}
                r={18}
                fill={accentColor}
                opacity={chartIn * 0.25}
              />
              <circle
                cx={travelPoint.x}
                cy={travelPoint.y}
                r={7}
                fill={accentColor}
                stroke="white"
                strokeWidth={2}
                opacity={chartIn}
              />
            </svg>
            <div
              style={{
                display: "flex",
                justifyContent: "space-between",
                marginTop: 12,
                fontSize: 26,
                color: "rgba(255,255,255,0.45)",
              }}
            >
              <span>{formatDate(bars[0].time).split(",")[0]}</span>
              <span>30 phiên gần nhất</span>
              <span>{formatDate(latest.time).split(",")[0]}</span>
            </div>
          </Interactive.Div>

          {/* Footer */}
          <Interactive.Div
            name="Footer"
            style={{
              marginTop: "auto",
              opacity: footerIn,
              width: "100%",
              display: "flex",
              justifyContent: "space-between",
              alignItems: "center",
              paddingTop: 32,
              borderTop: "1px solid rgba(255,255,255,0.08)",
              fontSize: 28,
              color: "rgba(255,255,255,0.5)",
            }}
          >
            <span>KLGD: {formatVolume(latest.volume)}</span>
            <span>Nguồn: VNDirect</span>
          </Interactive.Div>
        </Interactive.Div>
      </AbsoluteFill>
    </AbsoluteFill>
  );
};
