import { useMemo } from "react";
import {
  AbsoluteFill,
  CalculateMetadataFunction,
  Composition,
  Easing,
  Interactive,
  interpolate,
  staticFile,
  useCurrentFrame,
} from "remotion";
import { Audio } from "@remotion/media";
import { Input, ALL_FORMATS, UrlSource } from "mediabunny";
import { loadFont as loadTextFont } from "@remotion/google-fonts/BeVietnamPro";
import { loadFont as loadDataFont } from "@remotion/google-fonts/JetBrainsMono";
import { VNIndexBar } from "./fetchVNIndex";

// Two families with distinct roles (per frontend-design guidance): Be Vietnam
// Pro carries Vietnamese prose (dates, labels), JetBrains Mono carries every
// number and code — grounded in how an exchange ticker board actually reads.
const { fontFamily: textFont } = loadTextFont("normal", {
  weights: ["400", "500", "700"],
  subsets: ["latin", "vietnamese"],
});
const { fontFamily: dataFont } = loadDataFont("normal", {
  weights: ["500", "700", "800"],
  subsets: ["latin"],
});

// A near-black board casing rather than a decorative gradient — the palette
// of an LED exchange ticker, not a generic dark-mode SaaS card.
const COLORS = {
  bg: "#08090a",
  panel: "#0c0e0c",
  hairline: "rgba(255,255,255,0.09)",
  dim: "rgba(228,232,225,0.34)",
  faint: "rgba(228,232,225,0.18)",
};
// LED colors: green = tăng, red = giảm (international convention, by request), amber = đứng giá.
const LED = { up: "#2ee878", down: "#ff3b3b", flat: "#ffb020" };

const WIDTH = 1080;
const HEIGHT = 1080;
const CHART_WIDTH = WIDTH - 160;
const CHART_HEIGHT = 250;
const FPS = 30;
const DEFAULT_DURATION_IN_FRAMES = 60 * FPS;
const MAX_DURATION_IN_FRAMES = 90 * FPS; // safety cap in case the narration runs long
// Entrance animation settles by ~150f; everything after that is a slow ambient
// idle loop (glow orb, breathing badge, traveling chart marker) so the rest of
// the video isn't just a frozen frame.
const IDLE_START = 150;
// Matches the `from` prop on the <Audio> element below — the frame offset at
// which narration starts, used to convert beats.json timestamps to frames.
const AUDIO_START_FRAME = 20;

type Beat = { startMs: number; text: string };
type Beats = Partial<Record<"hook" | "headline" | "todayDetail" | "range30" | "trend30" | "outro", Beat>>;

type Props = {
  bars: VNIndexBar[];
  hasVoiceover: boolean;
  beats: Beats | null;
};

const calculateMetadata: CalculateMetadataFunction<Props> = async ({
  abortSignal,
}) => {
  // Data is pre-fetched into public/vnindex.json by `npm run fetch-data`
  // (see scripts/fetch-vnindex.mjs) — VNDirect's bot-protection blocks requests
  // made directly from the headless render browser, so we can't fetch it here.
  const response = await fetch(staticFile("vnindex.json"), { signal: abortSignal });

  if (!response.ok) {
    throw new Error(
      `Could not read public/vnindex.json (${response.status}). Run "npm run fetch-data" first.`,
    );
  }

  const bars = (await response.json()) as VNIndexBar[];

  // Voiceover is optional (generated by scripts/generate-voiceover.mjs via the
  // free Microsoft Edge TTS service — no API key needed), so check whether the
  // file exists rather than assuming it does.
  const voiceoverUrl = staticFile("voiceover/vnindex-latest.mp3");
  const voiceoverCheck = await fetch(voiceoverUrl, {
    method: "HEAD",
    signal: abortSignal,
  }).catch(() => null);
  const hasVoiceover = Boolean(voiceoverCheck && voiceoverCheck.ok);

  // Beats (per-sentence start times) are optional too — written by
  // generate-voiceover.mjs only when Edge TTS's sentence-boundary count
  // matched our script exactly. Used to sync visual "beats" to the narration.
  let beats: Beats | null = null;
  if (hasVoiceover) {
    const beatsResponse = await fetch(staticFile("voiceover/vnindex-latest.beats.json"), {
      signal: abortSignal,
    }).catch(() => null);
    if (beatsResponse && beatsResponse.ok) {
      beats = (await beatsResponse.json()) as Beats;
    }
  }

  // Size the video to the narration so it's never cut off mid-sentence: default
  // to 60s, but stretch (up to a cap) if the generated voiceover runs longer.
  let durationInFrames = DEFAULT_DURATION_IN_FRAMES;
  if (hasVoiceover) {
    try {
      const input = new Input({ formats: ALL_FORMATS, source: new UrlSource(voiceoverUrl) });
      const audioDurationInSeconds = await input.computeDuration();
      const neededFrames = Math.ceil((audioDurationInSeconds + 1) * FPS); // +1s tail padding
      durationInFrames = Math.min(
        MAX_DURATION_IN_FRAMES,
        Math.max(DEFAULT_DURATION_IN_FRAMES, neededFrames),
      );
    } catch {
      // If duration probing fails for any reason, fall back to the default
      // length rather than failing the whole render.
    }
  }

  return {
    durationInFrames,
    props: { bars, hasVoiceover, beats },
  };
};

export const VNIndexPostcardComposition = () => {
  return (
    <Composition
      id="VNIndexPostcard"
      component={VNIndexPostcard}
      durationInFrames={DEFAULT_DURATION_IN_FRAMES}
      fps={FPS}
      width={WIDTH}
      height={HEIGHT}
      defaultProps={{ bars: [] as VNIndexBar[], hasVoiceover: false, beats: null }}
      calculateMetadata={calculateMetadata}
    />
  );
};

const formatPoints = (n: number) =>
  n.toLocaleString("vi-VN", { minimumFractionDigits: 2, maximumFractionDigits: 2 });

const formatVolume = (v: number) => {
  if (v >= 1_000_000) return `${(v / 1_000_000).toFixed(1)} triệu CP`;
  if (v >= 1_000) return `${(v / 1_000).toFixed(1)} nghìn CP`;
  return `${v} CP`;
};

const formatDate = (unixSeconds: number) => {
  const d = new Date(unixSeconds * 1000);
  return d.toLocaleDateString("vi-VN", {
    weekday: "long",
    day: "2-digit",
    month: "2-digit",
    year: "numeric",
  });
};

// A quick attack / hold / decay pulse curve (0 -> 1 -> 0) starting at `startFrame`.
// Used to flash/emphasize an element right when the narrator mentions it.
const pulseAt = (
  frame: number,
  startFrame: number | undefined,
  attack = 6,
  hold = 8,
  decay = 26,
) => {
  if (startFrame === undefined) return 0;
  return interpolate(
    frame,
    [startFrame, startFrame + attack, startFrame + attack + hold, startFrame + attack + hold + decay],
    [0, 1, 1, 0],
    { extrapolateLeft: "clamp", extrapolateRight: "clamp" },
  );
};

export const VNIndexPostcard: React.FC<Props> = ({ bars, hasVoiceover, beats }) => {
  const frame = useCurrentFrame();

  // Chart geometry and the up/down-day tally only depend on `bars`, which is
  // constant for the whole video — memoize instead of recomputing every frame.
  // (Computed unconditionally, before the early return below, per the Rules of
  // Hooks — bars.length < 2 just yields empty/zeroed results, unused in that case.)
  const { points, linePath, areaPath, upDays, downDays } = useMemo(() => {
    if (!bars || bars.length < 2) {
      return { points: [], linePath: "", areaPath: "", upDays: 0, downDays: 0 };
    }

    const closes = bars.map((b) => b.close);
    const minClose = Math.min(...closes);
    const maxClose = Math.max(...closes);
    const range = maxClose - minClose || 1;

    const pts = bars.map((b, i) => ({
      x: (i / (bars.length - 1)) * CHART_WIDTH,
      y: CHART_HEIGHT - ((b.close - minClose) / range) * CHART_HEIGHT,
    }));

    const line = pts
      .map((p, i) => `${i === 0 ? "M" : "L"} ${p.x.toFixed(1)} ${p.y.toFixed(1)}`)
      .join(" ");
    const area = `${line} L ${CHART_WIDTH} ${CHART_HEIGHT} L 0 ${CHART_HEIGHT} Z`;

    let up = 0;
    let down = 0;
    for (let i = 1; i < bars.length; i++) {
      if (bars[i].close > bars[i - 1].close) up++;
      else if (bars[i].close < bars[i - 1].close) down++;
    }

    return { points: pts, linePath: line, areaPath: area, upDays: up, downDays: down };
  }, [bars]);

  if (!bars || bars.length < 2) {
    return (
      <AbsoluteFill
        style={{
          backgroundColor: COLORS.bg,
          color: "white",
          fontFamily: textFont,
          fontSize: 44,
          justifyContent: "center",
          alignItems: "center",
          textAlign: "center",
          padding: 80,
        }}
      >
        Không tải được dữ liệu VN-Index
      </AbsoluteFill>
    );
  }

  const latest = bars[bars.length - 1];
  const previous = bars[bars.length - 2];
  const change = latest.close - previous.close;
  const changePercent = (change / previous.close) * 100;
  const isUp = change > 0;
  const isFlat = Math.abs(change) < 0.005;

  // International convention (by request): up = green, down = red, flat = amber.
  const accentColor = isFlat ? LED.flat : isUp ? LED.up : LED.down;
  const trendLabel = isFlat ? "ĐI NGANG" : isUp ? "TĂNG" : "GIẢM";
  const trendArrow = isFlat ? "◆" : isUp ? "▲" : "▼";

  // --- Voiceover sync beats ---
  // Convert each beats.json timestamp (ms into the narration) to an absolute
  // frame, offset by where the <Audio> track actually starts.
  const beatFrame = (id: keyof Beats) => {
    const beat = beats?.[id];
    if (!beat) return undefined;
    return AUDIO_START_FRAME + Math.round((beat.startMs / 1000) * FPS);
  };
  const headlineBeat = beatFrame("headline");
  const todayDetailBeat = beatFrame("todayDetail");
  const range30Beat = beatFrame("range30");
  const trend30Beat = beatFrame("trend30");

  const headlinePulse = pulseAt(frame, headlineBeat);
  const todayDetailPulse = pulseAt(frame, todayDetailBeat);
  const range30Pulse = pulseAt(frame, range30Beat, 10, 14, 50);
  // The up/down-days stat row appears (and stays) once the narrator reaches it;
  // fall back to right after the chart finishes drawing when there's no sync data.
  const trendRowIn = interpolate(frame, [trend30Beat ?? 150, (trend30Beat ?? 150) + 18], [0, 1], {
    extrapolateLeft: "clamp",
    extrapolateRight: "clamp",
    easing: Easing.bezier(0.16, 1, 0.3, 1),
  });

  // --- Animations ---
  const cardIn = interpolate(frame, [0, 18], [0, 1], {
    extrapolateLeft: "clamp",
    extrapolateRight: "clamp",
    easing: Easing.bezier(0.16, 1, 0.3, 1),
  });

  const headerIn = interpolate(frame, [8, 26], [0, 1], {
    extrapolateLeft: "clamp",
    extrapolateRight: "clamp",
    easing: Easing.bezier(0.16, 1, 0.3, 1),
  });

  const numberProgress = interpolate(frame, [16, 55], [0, 1], {
    extrapolateLeft: "clamp",
    extrapolateRight: "clamp",
    easing: Easing.out(Easing.cubic),
  });
  const displayedClose = previous.close + (latest.close - previous.close) * numberProgress;

  const badgeIn = interpolate(frame, [45, 65], [0, 1], {
    extrapolateLeft: "clamp",
    extrapolateRight: "clamp",
    easing: Easing.bezier(0.16, 1, 0.3, 1),
  });

  const chartIn = interpolate(frame, [55, 130], [0, 1], {
    extrapolateLeft: "clamp",
    extrapolateRight: "clamp",
    easing: Easing.bezier(0.16, 1, 0.3, 1),
  });

  const footerIn = interpolate(frame, [110, 130], [0, 1], {
    extrapolateLeft: "clamp",
    extrapolateRight: "clamp",
    easing: Easing.bezier(0.16, 1, 0.3, 1),
  });

  // --- Ambient idle loop (keeps the remaining ~58s alive without new data) ---
  const idleT = Math.max(0, frame - IDLE_START) / FPS; // seconds since idle started
  const badgeBreathe = 1 + Math.sin(idleT * Math.PI * 0.5) * 0.02;

  // "LIVE" dot in the header — blinks at ~0.8Hz, like a board's update indicator.
  const liveBlink = Math.sin(frame * 0.17) > 0 ? 1 : 0.2;

  // A soft light band that sweeps down the board every ~7s, like an LED
  // panel's refresh scan. Fades in only once the entrance has settled.
  const scanLoopFrames = 7 * FPS;
  const scanProgress = (Math.max(0, frame - IDLE_START) % scanLoopFrames) / scanLoopFrames;
  const scanY = scanProgress * (HEIGHT - 96);
  const scanOpacity = interpolate(frame, [IDLE_START, IDLE_START + 20], [0, 1], {
    extrapolateLeft: "clamp",
    extrapolateRight: "clamp",
  });

  // Tiny per-frame brightness flicker on the big number, like a real LED
  // display never quite holding perfectly steady current.
  const digitFlicker = 0.96 + Math.sin(frame * 1.7) * 0.02 + Math.sin(frame * 3.1) * 0.015;

  // Marker that slowly travels back and forth along the trend line.
  const travelLoop = 6 * FPS; // 6s to cross the chart, then reverse
  const travelRaw = (Math.max(0, frame - IDLE_START) % (travelLoop * 2)) / travelLoop;
  const travelT = travelRaw <= 1 ? travelRaw : 2 - travelRaw; // 0->1->0 ping-pong

  // Chart geometry (points/linePath/areaPath/upDays/downDays) comes from the
  // useMemo block above — only travel-marker placement is computed per frame.
  const chartWidth = CHART_WIDTH;
  const chartHeight = CHART_HEIGHT;

  // Position of the ambient traveling marker along the polyline at travelT (0..1).
  const travelX = travelT * chartWidth;
  let travelPoint = points[points.length - 1];
  for (let i = 0; i < points.length - 1; i++) {
    if (travelX >= points[i].x && travelX <= points[i + 1].x) {
      const segT = (travelX - points[i].x) / (points[i + 1].x - points[i].x || 1);
      travelPoint = {
        x: travelX,
        y: points[i].y + (points[i + 1].y - points[i].y) * segT,
      };
      break;
    }
  }

  const ghostNumber = formatPoints(displayedClose).replace(/[0-9]/g, "8");

  return (
    <AbsoluteFill
      style={{
        fontFamily: textFont,
        background: `radial-gradient(120% 90% at 50% 28%, ${COLORS.panel} 0%, ${COLORS.bg} 72%)`,
      }}
    >
      {hasVoiceover && (
        <Audio src={staticFile("voiceover/vnindex-latest.mp3")} from={20} />
      )}

      <AbsoluteFill
        style={{
          justifyContent: "center",
          alignItems: "center",
        }}
      >
        <Interactive.Div
          name="Board"
          style={{
            width: WIDTH - 96,
            height: HEIGHT - 96,
            borderRadius: 10,
            border: `1px solid ${COLORS.hairline}`,
            background: COLORS.panel,
            boxShadow: "inset 0 0 90px rgba(0,0,0,0.45)",
            scale: interpolate(cardIn, [0, 1], [0.97, 1], {
              easing: Easing.bezier(0.16, 1, 0.3, 1),
              output: "perceptual-scale",
            }),
            opacity: cardIn,
            display: "flex",
            flexDirection: "column",
            padding: "40px 48px 30px",
            position: "relative",
            overflow: "hidden",
          }}
        >
          {/* Refresh-scan sweep, like an LED panel redrawing itself */}
          <div
            style={{
              position: "absolute",
              left: 0,
              right: 0,
              top: scanY - 70,
              height: 140,
              background: `linear-gradient(180deg, transparent, ${accentColor}12 45%, ${accentColor}1a 50%, ${accentColor}12 55%, transparent)`,
              opacity: scanOpacity,
              pointerEvents: "none",
            }}
          />

          {/* Header: ticker code plate (left) + session date (right) — not a
              decorative eyebrow, this is how a board actually labels itself. */}
          <Interactive.Div
            name="Header"
            style={{
              opacity: headerIn,
              translate: `0px ${interpolate(headerIn, [0, 1], [10, 0])}px`,
              display: "flex",
              justifyContent: "space-between",
              alignItems: "center",
              width: "100%",
            }}
          >
            <div style={{ display: "flex", alignItems: "center", gap: 10 }}>
              <div
                style={{
                  fontFamily: dataFont,
                  fontWeight: 700,
                  fontSize: 22,
                  letterSpacing: 0.5,
                  color: "white",
                  border: `1px solid ${COLORS.hairline}`,
                  borderRadius: 4,
                  padding: "5px 10px",
                }}
              >
                VNINDEX
              </div>
              <div style={{ fontSize: 19, color: COLORS.dim }}>Sàn HOSE</div>
            </div>
            <div style={{ display: "flex", alignItems: "center", gap: 16 }}>
              <div style={{ display: "flex", alignItems: "center", gap: 7 }}>
                <div
                  style={{
                    width: 7,
                    height: 7,
                    borderRadius: "50%",
                    background: LED.up,
                    opacity: liveBlink,
                    boxShadow: `0 0 6px ${LED.up}`,
                  }}
                />
                <span style={{ fontFamily: dataFont, fontSize: 13, letterSpacing: 1, color: COLORS.dim }}>
                  TRỰC TIẾP
                </span>
              </div>
              <div style={{ fontSize: 19, color: COLORS.dim, textTransform: "capitalize" }}>
                {formatDate(latest.time)}
              </div>
            </div>
          </Interactive.Div>

          {/* Big number — ghost digits (all "8") sit behind the lit value, the
              way an unpowered 7-segment display still shows its dark segments. */}
          <Interactive.Div
            name="BigNumber"
            style={{
              marginTop: 38,
              display: "grid",
            }}
          >
            <div
              style={{
                gridArea: "1 / 1",
                fontFamily: dataFont,
                fontWeight: 800,
                fontSize: 140,
                lineHeight: 1,
                letterSpacing: -2,
                color: `${accentColor}22`,
              }}
            >
              {ghostNumber}
            </div>
            <div
              style={{
                gridArea: "1 / 1",
                fontFamily: dataFont,
                fontWeight: 800,
                fontSize: 140,
                lineHeight: 1,
                letterSpacing: -2,
                color: "white",
                opacity: digitFlicker,
                scale: 1 + headlinePulse * 0.03,
                textShadow: `0 0 ${(16 + headlinePulse * 24) * digitFlicker}px ${accentColor}${headlinePulse > 0.05 ? "cc" : "66"}`,
              }}
            >
              {formatPoints(displayedClose)}
            </div>
          </Interactive.Div>

          {/* Change readout — a bracketed data tag, not a soft tinted pill */}
          <Interactive.Div
            name="ChangeBadge"
            style={{
              marginTop: 22,
              opacity: badgeIn,
              scale:
                interpolate(badgeIn, [0, 1], [0.95, 1], {
                  easing: Easing.spring({ damping: 200 }),
                  output: "perceptual-scale",
                }) *
                badgeBreathe *
                (1 + headlinePulse * 0.05),
              alignSelf: "flex-start",
              display: "flex",
              alignItems: "center",
              gap: 16,
              padding: "10px 20px",
              border: `1.5px solid ${accentColor}`,
              borderRadius: 6,
              fontFamily: dataFont,
              fontWeight: 700,
              fontSize: 32,
              color: accentColor,
            }}
          >
            <span>{trendArrow}</span>
            <span>
              {isUp ? "+" : ""}
              {formatPoints(change)}
            </span>
            <span style={{ width: 1, height: 24, background: `${accentColor}55` }} />
            <span>
              {isUp ? "+" : ""}
              {changePercent.toFixed(2)}%
            </span>
            <span style={{ fontFamily: textFont, fontSize: 18, fontWeight: 500, opacity: 0.85 }}>
              {trendLabel}
            </span>
          </Interactive.Div>

          {/* Chart — thin readout line over a hairline grid, not a soft glow card */}
          <Interactive.Div
            name="Chart"
            style={{
              marginTop: 34,
              width: chartWidth,
              scale: 1 + range30Pulse * 0.02,
              opacity: interpolate(chartIn, [0, 0.3], [0, 1], {
                extrapolateLeft: "clamp",
                extrapolateRight: "clamp",
              }),
            }}
          >
            <svg
              width={chartWidth}
              height={chartHeight}
              viewBox={`0 0 ${chartWidth} ${chartHeight}`}
            >
              <defs>
                <linearGradient id="areaFill" x1="0" y1="0" x2="0" y2="1">
                  <stop offset="0%" stopColor={accentColor} stopOpacity={0.22} />
                  <stop offset="100%" stopColor={accentColor} stopOpacity={0} />
                </linearGradient>
                <linearGradient id="sweepFill" x1="0" y1="0" x2="1" y2="0">
                  <stop offset="0%" stopColor="white" stopOpacity={0} />
                  <stop offset="50%" stopColor="white" stopOpacity={0.85} />
                  <stop offset="100%" stopColor="white" stopOpacity={0} />
                </linearGradient>
              </defs>
              {/* Reference gridlines, like a board's graph readout */}
              {[0.25, 0.5, 0.75].map((t) => (
                <line
                  key={t}
                  x1={0}
                  x2={chartWidth}
                  y1={chartHeight * t}
                  y2={chartHeight * t}
                  stroke={COLORS.hairline}
                  strokeWidth={1}
                />
              ))}
              <path d={areaPath} fill="url(#areaFill)" opacity={chartIn} />
              {/* Highlight sweep across the 30-day range, timed to the "range30" narration beat */}
              {range30Pulse > 0.01 && (
                <rect
                  x={
                    interpolate(
                      frame,
                      [range30Beat ?? 0, (range30Beat ?? 0) + 74],
                      [-60, chartWidth + 60],
                      { extrapolateLeft: "clamp", extrapolateRight: "clamp" },
                    ) - 60
                  }
                  y={-10}
                  width={120}
                  height={chartHeight + 20}
                  fill="url(#sweepFill)"
                  opacity={range30Pulse * 0.6}
                />
              )}
              <path
                d={linePath}
                fill="none"
                stroke={accentColor}
                strokeWidth={3}
                strokeLinecap="round"
                strokeLinejoin="round"
                pathLength={1}
                strokeDasharray={1}
                strokeDashoffset={interpolate(chartIn, [0, 1], [1, 0])}
              />
              {/* Ambient marker slowly traveling along the trend line */}
              <circle
                cx={travelPoint.x}
                cy={travelPoint.y}
                r={14}
                fill={accentColor}
                opacity={chartIn * 0.2}
              />
              <circle
                cx={travelPoint.x}
                cy={travelPoint.y}
                r={5}
                fill={accentColor}
                stroke="white"
                strokeWidth={1.5}
                opacity={chartIn}
              />
            </svg>
            <div
              style={{
                display: "flex",
                justifyContent: "space-between",
                marginTop: 10,
                fontSize: 19,
                color: COLORS.dim,
              }}
            >
              <span>{formatDate(bars[0].time).split(",")[0]}</span>
              <span>30 phiên gần nhất</span>
              <span>{formatDate(latest.time).split(",")[0]}</span>
            </div>
          </Interactive.Div>

          {/* Up/down days — one bracketed row, split by a hairline, matching the
              change readout's visual language instead of two loose pills. */}
          <Interactive.Div
            name="TrendDaysRow"
            style={{
              marginTop: 18,
              opacity: trendRowIn,
              translate: `0px ${interpolate(trendRowIn, [0, 1], [10, 0])}px`,
              display: "flex",
              border: `1px solid ${COLORS.hairline}`,
              borderRadius: 6,
              overflow: "hidden",
            }}
          >
            <div
              style={{
                flex: 1,
                display: "flex",
                alignItems: "center",
                justifyContent: "center",
                gap: 10,
                padding: "10px 12px",
                borderRight: `1px solid ${COLORS.hairline}`,
              }}
            >
              <span style={{ fontFamily: dataFont, fontWeight: 700, fontSize: 22, color: LED.up }}>
                ▲ {upDays}
              </span>
              <span style={{ fontSize: 18, color: COLORS.dim }}>phiên tăng</span>
            </div>
            <div
              style={{
                flex: 1,
                display: "flex",
                alignItems: "center",
                justifyContent: "center",
                gap: 10,
                padding: "10px 12px",
              }}
            >
              <span style={{ fontFamily: dataFont, fontWeight: 700, fontSize: 22, color: LED.down }}>
                ▼ {downDays}
              </span>
              <span style={{ fontSize: 18, color: COLORS.dim }}>phiên giảm</span>
            </div>
          </Interactive.Div>

          {/* Footer */}
          <Interactive.Div
            name="Footer"
            style={{
              marginTop: "auto",
              opacity: footerIn,
              width: "100%",
              display: "flex",
              justifyContent: "space-between",
              alignItems: "baseline",
              paddingTop: 18,
              borderTop: `1px solid ${COLORS.hairline}`,
              fontSize: 18,
              color: COLORS.dim,
            }}
          >
            <span>
              KLGD{" "}
              <span
                style={{
                  fontFamily: dataFont,
                  fontWeight: 700,
                  fontSize: 19,
                  color: `rgba(255,255,255,${0.75 + todayDetailPulse * 0.25})`,
                  scale: 1 + todayDetailPulse * 0.06,
                  display: "inline-block",
                }}
              >
                {formatVolume(latest.volume)}
              </span>
            </span>
            <span style={{ color: COLORS.faint }}>Nguồn: VNDirect</span>
          </Interactive.Div>
        </Interactive.Div>
      </AbsoluteFill>
    </AbsoluteFill>
  );
};
